In [5]:
import pandas as pd

In [8]:
college = pd.read_csv('College.csv')

In [11]:
college.head()

,Name,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

### Top 3 colleges by enrollement

In [16]:
college.sort_values(by='Enroll', ascending=False).head(3)

,Name,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
581,Texas A&M Univ. at College Station,No,14474,10519,6392,49,85,31643,2798,5130,3412,600,2144,89,91,23.1,29,8471,69
366,Michigan State University,No,18114,15096,6180,23,57,26640,4120,10658,3734,504,600,93,95,14.0,9,10520,71
461,Purdue University at West Lafayette,No,21804,18744,5874,29,60,26213,4065,9556,3990,570,1060,86,86,18.2,15,8604,67

### Top 3 Public vs Private College Enrollement

In [24]:
college.loc[college['Private'] == 'Yes'].sort_values(by='Enroll', ascending=False).head(3)[['Name', 'Enroll']]

                                  Name  Enroll
69   Brigham Young University at Provo    4615
59                   Boston University    3810
614             University of Delaware    3252

In [23]:
college.loc[college['Private'] == 'No'].sort_values(by='Enroll', ascending=False).head(3)[['Name', 'Enroll']]

                                    Name  Enroll
581   Texas A&M Univ. at College Station    6392
366            Michigan State University    6180
461  Purdue University at West Lafayette    5874

###  Colleges Sorted by Enrollement Rate

In [29]:
college['enrollment_rate'] = college['Enroll'] / college['Accept'] * 100
college.sort_values(by='enrollment_rate', ascending=False).head(5)[['Name', 'enrollment_rate']]

                                 Name  enrollment_rate
77     California Lutheran University       100.000000
66             Brewton-Parker College        97.882736
376  Mississippi University for Women        93.827160
447                Peru State College        91.417166
275       Indiana Wesleyan University        86.524823